# **TELECOM X PARTE 2 - PREDICCIÓN DE CANCELACIÓN CHURN📉**

## **🛠️ Preparación de los Datos**

**Instalamos la biblioteca [pandas](https://pandas.pydata.org/) para realizar el análisis de datos**

In [132]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**Se importó pandas para realizar la extracción desde el archivo cargado en el entorno de trabajo, para el análisis y visualización de los datos. En conjunto de [IPython.display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display) módulo con su función principal [display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display).Permitiendo mostrar un objeto Python, determinando automáticamente la mejor representación para el objeto**

In [133]:
import pandas as pd
from IPython.display import display


try:
    #Cargamos los datos
    datos = '/content/Analisis_Telecom_X_Limpio_y_Transformado'
    df_telecomx = pd.read_csv(datos)

except Exception as e:
    # Archivo no cargado en el entorno de trabajo
    print(f'Error al extraer los datos: {e}')

else:
    # Usamos display() para ver el DataFrame formateado si no hay error
    pd.set_option('display.max_columns', None)
    display(df_telecomx.head())

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PhoneService,MultipleLines,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,ChargesDaily_Total
0,0002-ORFBO,0,Female,0,1,1,9,DSL,0,1,0,1,1,0,1,0,One year,1,Mailed check,65.6,593.30,2.20
1,0003-MKNFE,0,Male,0,0,0,9,DSL,0,0,0,0,0,1,1,1,Month-to-month,0,Mailed check,59.9,542.40,2.01
2,0004-TLHLJ,1,Male,0,0,0,4,Fiber optic,0,0,1,0,0,0,1,0,Month-to-month,1,Electronic check,73.9,280.85,2.34
3,0011-IGKFF,1,Male,1,1,0,13,Fiber optic,0,1,1,0,1,1,1,0,Month-to-month,1,Electronic check,98.0,1237.85,3.17
4,0013-EXCHZ,1,Female,1,1,0,3,Fiber optic,0,0,0,1,1,0,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.97

**Eliminamos la columna CustomerID, ya que para los modelos de predicción esta columna no aporta valor o puede afectar al mismo**

In [134]:
try:
    #Realizamos la copia del DataFrame original
    df_telecomx_nuevo = df_telecomx.copy()

    #Eliminamos la columna innecesaria
    df_telecomx_nuevo = df_telecomx_nuevo.drop(columns='customerID')
except Exception as e:
    print(f'Error al eliminar la columna customerID: {e}')
else:
    #Mostramos el resultado
    display(df_telecomx_nuevo.head())

,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PhoneService,MultipleLines,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,ChargesDaily_Total
0,0,Female,0,1,1,9,DSL,0,1,0,1,1,0,1,0,One year,1,Mailed check,65.6,593.30,2.20
1,0,Male,0,0,0,9,DSL,0,0,0,0,0,1,1,1,Month-to-month,0,Mailed check,59.9,542.40,2.01
2,1,Male,0,0,0,4,Fiber optic,0,0,1,0,0,0,1,0,Month-to-month,1,Electronic check,73.9,280.85,2.34
3,1,Male,1,1,0,13,Fiber optic,0,1,1,0,1,1,1,0,Month-to-month,1,Electronic check,98.0,1237.85,3.17
4,1,Female,1,1,0,3,Fiber optic,0,0,0,1,1,0,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.97

In [135]:
try:
  #Separamos el conjunto de Datos en 2 partes:

  # y: alamcenara la variable objetivo o interés
  y = df_telecomx_nuevo['Churn']

  # X: almacenara las variables explicativas
  X = df_telecomx_nuevo.drop(columns='Churn')
except Exception as e:
  print(f'Error al tratar la variable objetivo: {e}')
else:
  print('Cambios realizados exitosamente')

Cambios realizados exitosamente

**Utilizamos el método [OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) de la biblioteca de aprendizaje automático [Scikit-learn](https://scikit-learn.org/) para tratar las variables categorías del conjunto de datos convirtiéndolas en valores numéricos para el proceso de Machine Learning, ya que los modelos de aprendizaje automático trabajan con datos numéricos.**

In [136]:
try:
    #Importamos la funciones:
    from sklearn.compose import make_column_transformer
    from sklearn.preprocessing import OneHotEncoder

    # Estructuramos la tranformacion y parametros para tratar las variables categoricas
    transformer = make_column_transformer((OneHotEncoder(drop='if_binary'),
                  ['gender','InternetService','Contract','PaymentMethod']),
                  remainder='passthrough', sparse_threshold=0, force_int_remainder_cols=False)

    #Variable que contiene el nombre de las columnas explicativas
    colums = X.columns

    #Realizamos el ajuste y asignacion del resultado en la tranformacion de las variables explicativas
    X = transformer.fit_transform(X)

    #Creamos DataFrame de visualización para ver el resultado de la transformación
    df_demostracion= pd.DataFrame(X,columns=transformer.get_feature_names_out(colums))

except Exception as e:
    print(f'Error al tratar las variables categorías: {e}')
else:
  #Mostramos el DataFrame para ver el tratamiento
  display(df_demostracion.head())

,onehotencoder__gender_Male,onehotencoder__InternetService_DSL,onehotencoder__InternetService_Fiber optic,onehotencoder__InternetService_No,onehotencoder__Contract_Month-to-month,onehotencoder__Contract_One year,onehotencoder__Contract_Two year,onehotencoder__PaymentMethod_Bank transfer (automatic),onehotencoder__PaymentMethod_Credit card (automatic),onehotencoder__PaymentMethod_Electronic check,onehotencoder__PaymentMethod_Mailed check,remainder__SeniorCitizen,remainder__Partner,remainder__Dependents,remainder__tenure,remainder__OnlineSecurity,remainder__OnlineBackup,remainder__DeviceProtection,remainder__TechSupport,remainder__StreamingTV,remainder__StreamingMovies,remainder__PhoneService,remainder__MultipleLines,remainder__PaperlessBilling,remainder__ChargesMonthly,remainder__ChargesTotal,remainder__ChargesDaily_Total
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,9.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,65.6,593.30,2.20
1,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,59.9,542.40,2.01
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,73.9,280.85,2.34
3,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,13.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,98.0,1237.85,3.17
4,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,83.9,267.40,2.97

**Calculamos la proporción de clientes que cancelaron en relación con los que permanecieron activos. Evaluando si existe un desbalance entre las clases, ya que esto puede impactar en los modelos predictivos y en el análisis de los resultados.**

In [137]:
try:
  #Creamos variable que contiene la cantidad por tipo
  proporcion = y.value_counts()
except Exception as e:
  print(f'Error revisar la variable objetivo: {e}')
else:
  #Mostramos el resultado
  display(proporcion)

Churn
0    5376
1    1891
Name: count, dtype: int64